// <auto-generated />
using System;
using AppServicios.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppServicios.Api.Migrations
{
    [DbContext(typeof(AppServiciosDbContext))]
    [Migration("20260403012823_AddUserNotifications")]
    partial class AddUserNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppServicios.Api.Domain.Certificado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaOtorgamiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProfesionalId")
                        .HasColumnType("integer");

                    b.Property<string>("UrlDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Verificado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ProfesionalId");

                    b.ToTable("Certificados");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CalificacionPromedioProfesionales")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GastoPorMes")
                        .HasColumnType("numeric");

                    b.Property<double>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<string>("Preferencias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RecibeNotificaciones")
                        .HasColumnType("boolean");

                    b.Property<int>("TotalServiciosContratados")
                        .HasColumnType("integer");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Direccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Piso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Direcciones");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SolicitudTrabajoId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.PagoProfesional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenciaExterna")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReferenciaExterna")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("PagosProfesionales");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Profesional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AceptaTrabajoLejano")
                        .HasColumnType("boolean");

                    b.Property<int>("AñosExperiencia")
                        .HasColumnType("integer");

                    b.Property<decimal>("BonoPorDistancia")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CalificacionPromedio")
                        .HasColumnType("numeric");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("GananciaMensualActual")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GananciaMensualObjetivo")
                        .HasColumnType("numeric");

                    b.Property<double>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<int>("RadioAlcanceKm")
                        .HasColumnType("integer");

                    b.Property<decimal>("TarifaBase")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalTrabajos")
                        .HasColumnType("integer");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Profesionales");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Rubro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rubros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Servicios eléctricos",
                            Icono = "electricidad",
                            Nombre = "Electricidad"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Servicios de plomería",
                            Icono = "plomeria",
                            Nombre = "Plomería"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Niñeras y cuidadores",
                            Icono = "cuidados-ninos",
                            Nombre = "Cuidados de Niños"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Cuidados de salud",
                            Icono = "enfermeria",
                            Nombre = "Enfermería"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "Reparación de vehículos",
                            Icono = "mecanica",
                            Nombre = "Mecánica"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Descripcion = "Trabajo en metal",
                            Icono = "metalurgia",
                            Nombre = "Metalurgia"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Descripcion = "Servicios de soldadura",
                            Icono = "soldadura",
                            Nombre = "Soldadura"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Descripcion = "Reparaciones técnicas",
                            Icono = "tecnica",
                            Nombre = "Técnica"
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Descripcion = "Software, soporte IT, redes y servicios digitales",
                            Icono = "tecnologia-sistemas",
                            Nombre = "Tecnología y Sistemas"
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Descripcion = "Atención clínica, cuidados y asistencia sanitaria",
                            Icono = "salud-enfermeria",
                            Nombre = "Salud y Enfermería"
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            Descripcion = "Procesos productivos, planta y operación técnica",
                            Icono = "produccion-manufactura",
                            Nombre = "Producción, Manufactura y Operarios"
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            Descripcion = "Ventas, reparto, logística y atención comercial",
                            Icono = "comercio-logistica",
                            Nombre = "Comercio Ventas y Logística"
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            Descripcion = "Gestión administrativa, contable y financiera",
                            Icono = "administracion-finanzas",
                            Nombre = "Administración Contabilidad y Finanzas"
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            Descripcion = "Hotelería, turismo, cocina y atención gastronómica",
                            Icono = "hosteleria-gastronomia",
                            Nombre = "Hostelería Turismo y Gastronomía"
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            Descripcion = "Obra, mantenimiento general y servicios técnicos",
                            Icono = "construccion-servicios",
                            Nombre = "Construcción y Servicios Generales"
                        });
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioSugerido")
                        .HasColumnType("numeric");

                    b.Property<int>("RubroId")
                        .HasColumnType("integer");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RubroId");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.SolicitudTrabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CalificacionCliente")
                        .HasColumnType("integer");

                    b.Property<int?>("CalificacionProfesional")
                        .HasColumnType("integer");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("ComentarioCliente")
                        .HasColumnType("text");

                    b.Property<string>("ComentarioProfesional")
                        .HasColumnType("text");

                    b.Property<decimal?>("CostoTraslado")
                        .HasColumnType("numeric");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("DistanciaKm")
                        .HasColumnType("numeric");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaAceptacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaCompletacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRequerida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Incentivo")
                        .HasColumnType("numeric");

                    b.Property<double>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<decimal>("PresupuestoEstimado")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PresupuestoFinal")
                        .HasColumnType("numeric");

                    b.Property<int?>("ProfesionalId")
                        .HasColumnType("integer");

                    b.Property<int>("ServicioId")
                        .HasColumnType("integer");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProfesionalId");

                    b.HasIndex("ServicioId");

                    b.ToTable("SolicitudesTrabajo");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVerificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RecibeNotificaciones")
                        .HasColumnType("boolean");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("VerificadoRenaper")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DNI")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProfesionalRubro", b =>
                {
                    b.Property<int>("ProfesionalesId")
                        .HasColumnType("integer");

                    b.Property<int>("RubrosProfesionalesId")
                        .HasColumnType("integer");

                    b.HasKey("ProfesionalesId", "RubrosProfesionalesId");

                    b.HasIndex("RubrosProfesionalesId");

                    b.ToTable("ProfesionalRubro");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Certificado", b =>
                {
                    b.HasOne("AppServicios.Api.Domain.Profesional", "Profesional")
                        .WithMany("Certificados")
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Cliente", b =>
                {
                    b.HasOne("AppServicios.Api.Domain.Usuario", "Usuario")
                        .WithOne("Cliente")
                        .HasForeignKey("AppServicios.Api.Domain.Cliente", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Direccion", b =>
                {
                    b.HasOne("AppServicios.Api.Domain.Cliente", "Cliente")
                        .WithMany("Direcciones")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Notificacion", b =>
                {
                    b.HasOne("AppServicios.Api.Domain.Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.PagoProfesional", b =>
                {
                    b.HasOne("AppServicios.Api.Domain.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Profesional", b =>
                {
                    b.HasOne("AppServicios.Api.Domain.Usuario", "Usuario")
                        .WithOne("Profesional")
                        .HasForeignKey("AppServicios.Api.Domain.Profesional", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Servicio", b =>
                {
                    b.HasOne("AppServicios.Api.Domain.Rubro", "Rubro")
                        .WithMany("Servicios")
                        .HasForeignKey("RubroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rubro");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.SolicitudTrabajo", b =>
                {
                    b.HasOne("AppServicios.Api.Domain.Cliente", "Cliente")
                        .WithMany("SolicitudesTrabajo")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppServicios.Api.Domain.Profesional", "Profesional")
                        .WithMany("SolicitudesTrabajo")
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AppServicios.Api.Domain.Servicio", "Servicio")
                        .WithMany("SolicitudesTrabajo")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Profesional");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("ProfesionalRubro", b =>
                {
                    b.HasOne("AppServicios.Api.Domain.Profesional", null)
                        .WithMany()
                        .HasForeignKey("ProfesionalesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppServicios.Api.Domain.Rubro", null)
                        .WithMany()
                        .HasForeignKey("RubrosProfesionalesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Cliente", b =>
                {
                    b.Navigation("Direcciones");

                    b.Navigation("SolicitudesTrabajo");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Profesional", b =>
                {
                    b.Navigation("Certificados");

                    b.Navigation("SolicitudesTrabajo");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Rubro", b =>
                {
                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Servicio", b =>
                {
                    b.Navigation("SolicitudesTrabajo");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Usuario", b =>
                {
                    b.Navigation("Cliente");

                    b.Navigation("Notificaciones");

                    b.Navigation("Profesional");
                });
#pragma warning restore 612, 618
        }
    }
}
