// <auto-generated />
using System;
using AppServicios.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppServicios.Api.Migrations
{
    [DbContext(typeof(AppServiciosDbContext))]
    partial class AppServiciosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppServicios.Api.Domain.Certificado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaOtorgamiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfesionalId")
                        .HasColumnType("int");

                    b.Property<string>("UrlDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Verificado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ProfesionalId");

                    b.ToTable("Certificados");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CalificacionPromedioProfesionales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GastoPorMes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Latitud")
                        .HasColumnType("float");

                    b.Property<double>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("Preferencias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RecibeNotificaciones")
                        .HasColumnType("bit");

                    b.Property<int>("TotalServiciosContratados")
                        .HasColumnType("int");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Direccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitud")
                        .HasColumnType("float");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Piso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Direcciones");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Profesional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AceptaTrabajoLejano")
                        .HasColumnType("bit");

                    b.Property<int>("AñosExperiencia")
                        .HasColumnType("int");

                    b.Property<decimal>("BonoPorDistancia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CalificacionPromedio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GananciaMensualActual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GananciaMensualObjetivo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Latitud")
                        .HasColumnType("float");

                    b.Property<double>("Longitud")
                        .HasColumnType("float");

                    b.Property<int>("RadioAlcanceKm")
                        .HasColumnType("int");

                    b.Property<decimal>("TarifaBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalTrabajos")
                        .HasColumnType("int");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Profesionales");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Rubro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rubros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Servicios eléctricos",
                            Icono = "electricidad",
                            Nombre = "Electricidad"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Servicios de plomería",
                            Icono = "plomeria",
                            Nombre = "Plomería"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Niñeras y cuidadores",
                            Icono = "cuidados-ninos",
                            Nombre = "Cuidados de Niños"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Cuidados de salud",
                            Icono = "enfermeria",
                            Nombre = "Enfermería"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "Reparación de vehículos",
                            Icono = "mecanica",
                            Nombre = "Mecánica"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Descripcion = "Trabajo en metal",
                            Icono = "metalurgia",
                            Nombre = "Metalurgia"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Descripcion = "Servicios de soldadura",
                            Icono = "soldadura",
                            Nombre = "Soldadura"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Descripcion = "Reparaciones técnicas",
                            Icono = "tecnica",
                            Nombre = "Técnica"
                        });
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioSugerido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RubroId")
                        .HasColumnType("int");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RubroId");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.SolicitudTrabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CalificacionCliente")
                        .HasColumnType("int");

                    b.Property<int?>("CalificacionProfesional")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("ComentarioCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComentarioProfesional")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CostoTraslado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DistanciaKm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaAceptacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCompletacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRequerida")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Incentivo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Latitud")
                        .HasColumnType("float");

                    b.Property<double>("Longitud")
                        .HasColumnType("float");

                    b.Property<decimal>("PresupuestoEstimado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PresupuestoFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProfesionalId")
                        .HasColumnType("int");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProfesionalId");

                    b.HasIndex("ServicioId");

                    b.ToTable("SolicitudesTrabajo");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVerificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("VerificadoRenaper")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DNI")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProfesionalRubro", b =>
                {
                    b.Property<int>("ProfesionalesId")
                        .HasColumnType("int");

                    b.Property<int>("RubrosProfesionalesId")
                        .HasColumnType("int");

                    b.HasKey("ProfesionalesId", "RubrosProfesionalesId");

                    b.HasIndex("RubrosProfesionalesId");

                    b.ToTable("ProfesionalRubro");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Certificado", b =>
                {
                    b.HasOne("AppServicios.Api.Domain.Profesional", "Profesional")
                        .WithMany("Certificados")
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Cliente", b =>
                {
                    b.HasOne("AppServicios.Api.Domain.Usuario", "Usuario")
                        .WithOne("Cliente")
                        .HasForeignKey("AppServicios.Api.Domain.Cliente", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Direccion", b =>
                {
                    b.HasOne("AppServicios.Api.Domain.Cliente", "Cliente")
                        .WithMany("Direcciones")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Profesional", b =>
                {
                    b.HasOne("AppServicios.Api.Domain.Usuario", "Usuario")
                        .WithOne("Profesional")
                        .HasForeignKey("AppServicios.Api.Domain.Profesional", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Servicio", b =>
                {
                    b.HasOne("AppServicios.Api.Domain.Rubro", "Rubro")
                        .WithMany("Servicios")
                        .HasForeignKey("RubroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rubro");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.SolicitudTrabajo", b =>
                {
                    b.HasOne("AppServicios.Api.Domain.Cliente", "Cliente")
                        .WithMany("SolicitudesTrabajo")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppServicios.Api.Domain.Profesional", "Profesional")
                        .WithMany("SolicitudesTrabajo")
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AppServicios.Api.Domain.Servicio", "Servicio")
                        .WithMany("SolicitudesTrabajo")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Profesional");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("ProfesionalRubro", b =>
                {
                    b.HasOne("AppServicios.Api.Domain.Profesional", null)
                        .WithMany()
                        .HasForeignKey("ProfesionalesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppServicios.Api.Domain.Rubro", null)
                        .WithMany()
                        .HasForeignKey("RubrosProfesionalesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Cliente", b =>
                {
                    b.Navigation("Direcciones");

                    b.Navigation("SolicitudesTrabajo");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Profesional", b =>
                {
                    b.Navigation("Certificados");

                    b.Navigation("SolicitudesTrabajo");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Rubro", b =>
                {
                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Servicio", b =>
                {
                    b.Navigation("SolicitudesTrabajo");
                });

            modelBuilder.Entity("AppServicios.Api.Domain.Usuario", b =>
                {
                    b.Navigation("Cliente")
                        .IsRequired();

                    b.Navigation("Profesional")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
